name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Make Gradlew Executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Login to Docker Hub
        run: echo $DOCKER_ACCESS_TOKEN | docker login --username $DOCKER_USERNAME --password-stdin


      - name: Build and push Docker image
        if: success()
        run: |
          echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$(echo -n "$DOCKER_USERNAME:$DOCKER_ACCESS_TOKEN" | base64)\"}}}" > $HOME/.docker/config.json
          docker build -t abdeljalilelhassani/csa-app:latest .
          docker push abdeljalilelhassani/csa-app:latest
